services:

  db:
    image: postgres:14-alpine
    container_name: postgres-coope
    
    restart: always 
    environment:
      POSTGRES_USER: prueba-usuario
      POSTGRES_PASSWORD: prueba-pass
      POSTGRES_DB: prueba-coope
    ports:

      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


